coverage:
  round: up
  precision: 2
  range: 30..100
  status:
    patch: false
    project:
      default:
        informational: true
      ncrl-cli:
        informational: true
        paths:
          - packages/ncrl-cli
      ncrl-json:
        informational: true
        paths:
          - packages/ncrl-json
